---
output: pdf_document
---
# EDAV Project #1: "The Class"
First project in Exploratory Data Analysis &amp; Visualisation course is targeted to analyse the data frame containing survey responses from all the students taking the class regarding their technical skills, level of familiarity with certain programming languages and frameworks as well as some demographic statistics regarding their background and school affiliation within Columbia University.

## Reading the input files and creating a clean data set to work with
The input data frame contains ***114 observations*** and ***38 variables***.

We wrote a function called **tidydata** that takes in a filename (with the path of the input file) and returns a clean data frame that we can start analyzing.

This function is stored as a script file named "tidydata.R" in our working directory that we need to source and run before we start the analysis.

```{r message = FALSE}
#assuming that you have set your working directory to where you downloaded the input data
filename<-"Survey+Response.xlsx"
source("tidydata.R")
df<-tidydata(filename)
```
Now this data frame **df** has the data we want to start analyzing.


## Ideas for Analysis

**1ST IDEA:** As far as we have information about the program affiliation of each student, we can map it to different skills students claim to have, demonstrating interesting statistics on which tools are more popular within certain fields of knowledge and how the choice of a primary programming language correlates with different scientific backgrounds observed over the students taking EDA&V course.


**2ND IDEA** In addition to this, we will analyze correlation between knowledge of different tech tools. A heat map can then summarize our findings and show if there are interesting patterns in this data


**3RD IDEA** Create Exploratory Visualizations
** Gender & Program Plot **
The function GenderProgramPlot takes in the clean data frame and returns a ggplot object that will plot the break down of students by gender and program.

